# Generated by Django 5.0.7 on 2024-07-21 00:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_watchlist_delete_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='watchlist',
            field=models.ManyToManyField(blank=True, null=True, related_name='Watchlisted', to=settings.AUTH_USER_MODEL),
        ),
    ]
