# Generated by Django 5.0.7 on 2024-07-22 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_remove_product_category_delete_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='H', max_length=64),
        ),
    ]
