# Generated by Django 5.0.7 on 2024-07-22 19:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
